version: "3.9"

services:
  demo-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: demo-app-gastos:0.1.1
    container_name: demo-app-gastos
    ports:
      - "8080:8080"
    volumes:
      - demo-app-uploads:/app/uploads

volumes:
  demo-app-uploads: